server:
  servlet:
    context-path: /chat
    session:
      timeout: P30D
  port: 8550

#个人配置
self-conf:
  #检查连接的超时时间
  connect-timeout: 60000
  #断开链接时间
  close-timeout: 3600000
  #最大客户端数量
  max-client-num: 20
  #session最大保存信息数
  max-session-message-num: 50
  #上传文件保存地址，供下载管理
  upload-file-path: /tmp/chattmp

  #最大存储文件大小,单位为m
  max-file-size : 500
  #最大请求文件大小,单位为m
  max-request-size : 500

spring:
  jackson:
    default-property-inclusion: non_null
  #模板引擎
  thymeleaf:
    cache: false
    check-template: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  mvc:
    favicon:
      enabled: false

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  #只允许本机的9001端口操作监控
  server:
    port: 9001
    address: 127.0.0.1

